// Code generated by Kitex v0.14.1. DO NOT EDIT.

package noteservice

import (
	"context"
	notes "ex4_noteservice/kitex_gen/notes"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateNote(ctx context.Context, request *notes.CreateNoteRequest, callOptions ...callopt.Option) (r *notes.Note, err error)
	GetNote(ctx context.Context, request *notes.GetNoteRequest, callOptions ...callopt.Option) (r *notes.Note, err error)
	ListNotes(ctx context.Context, user string, callOptions ...callopt.Option) (r []*notes.Note, err error)
	DeleteNote(ctx context.Context, request *notes.DeleteNoteRequest, callOptions ...callopt.Option) (r bool, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kNoteServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNoteServiceClient struct {
	*kClient
}

func (p *kNoteServiceClient) CreateNote(ctx context.Context, request *notes.CreateNoteRequest, callOptions ...callopt.Option) (r *notes.Note, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateNote(ctx, request)
}

func (p *kNoteServiceClient) GetNote(ctx context.Context, request *notes.GetNoteRequest, callOptions ...callopt.Option) (r *notes.Note, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNote(ctx, request)
}

func (p *kNoteServiceClient) ListNotes(ctx context.Context, user string, callOptions ...callopt.Option) (r []*notes.Note, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListNotes(ctx, user)
}

func (p *kNoteServiceClient) DeleteNote(ctx context.Context, request *notes.DeleteNoteRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteNote(ctx, request)
}
