// Code generated by Kitex v0.14.1. DO NOT EDIT.

package userservice

import (
	"context"
	user "ex5_cleanarchi/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateUser(ctx context.Context, request *user.CreateUserRequest, callOptions ...callopt.Option) (r *user.User, err error)
	Getuser(ctx context.Context, request *user.GetUserRequest, callOptions ...callopt.Option) (r *user.User, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) CreateUser(ctx context.Context, request *user.CreateUserRequest, callOptions ...callopt.Option) (r *user.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, request)
}

func (p *kUserServiceClient) Getuser(ctx context.Context, request *user.GetUserRequest, callOptions ...callopt.Option) (r *user.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Getuser(ctx, request)
}
