// Code generated by Kitex v0.14.1. DO NOT EDIT.

package videoservice

import (
	"context"
	videos "ex6_LVRS/kitex_gen/videos"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddVideo(ctx context.Context, request *videos.AddVideoRequest, callOptions ...callopt.Option) (r *videos.Video, err error)
	ManualOverride(ctx context.Context, request *videos.ManualOverrideRequest, callOptions ...callopt.Option) (r bool, err error)
	GetVideo(ctx context.Context, request *videos.GetVideoRequest, callOptions ...callopt.Option) (r *videos.Video, err error)
	GetVideos(ctx context.Context, request *videos.GetVideoListRequest, callOptions ...callopt.Option) (r *videos.VideoList, err error)
	DeleteVideo(ctx context.Context, request *videos.DeleteVideoRequest, callOptions ...callopt.Option) (r bool, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) AddVideo(ctx context.Context, request *videos.AddVideoRequest, callOptions ...callopt.Option) (r *videos.Video, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddVideo(ctx, request)
}

func (p *kVideoServiceClient) ManualOverride(ctx context.Context, request *videos.ManualOverrideRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ManualOverride(ctx, request)
}

func (p *kVideoServiceClient) GetVideo(ctx context.Context, request *videos.GetVideoRequest, callOptions ...callopt.Option) (r *videos.Video, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideo(ctx, request)
}

func (p *kVideoServiceClient) GetVideos(ctx context.Context, request *videos.GetVideoListRequest, callOptions ...callopt.Option) (r *videos.VideoList, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideos(ctx, request)
}

func (p *kVideoServiceClient) DeleteVideo(ctx context.Context, request *videos.DeleteVideoRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteVideo(ctx, request)
}
